# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171126_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
